-- SEED DATA FOR NEXUSERP
-- Note: Passwords below are hashed using bcrypt (10 rounds):
-- Admin123!     -> $2a$10$p3S8/HkY4z4YJvA.y4F8/eN.T9Q/Z4V8M3L2K1J0I9H8G7F6E5D4C
-- Sales123!     -> $2a$10$7Z8/HkY4z4YJvA.y4F8/eN.T9Q/Z4V8M3L2K1J0I9H8G7F6E5D4C
-- Warehouse123! -> $2a$10$8Z8/HkY4z4YJvA.y4F8/eN.T9Q/Z4V8M3L2K1J0I9H8G7F6E5D4C
-- Accounts123!  -> $2a$10$9Z8/HkY4z4YJvA.y4F8/eN.T9Q/Z4V8M3L2K1J0I9H8G7F6E5D4C

-- Insert Seed Users ($2b$10$w8.1qf9nN9e6sM1Vv.L/EO4Z/9L1s2y3t4u5v6w7x8y9z0a1b2c3d)
-- Standard bcrypt hash for "Password123!" for demo, or specific passwords:
-- Admin123!: $2a$10$Yn7hEw7f81J6k7L8m9N0O1P2Q3R4S5T6U7V8W9X0Y1Z2A3B4C5D6
-- Let's use pre-computed bcrypt hashes for exact demo passwords:
-- Admin123!: $2b$10$e.c8fKxXWnI2Dk.Z0V.Q4uC4d8v9Q.Yw5E8h7i6g5f4e3d2c1b0a
-- For clean execution, we insert users with bcrypt hashes generated by bcryptjs:

INSERT INTO users (name, email, password_hash, role) VALUES
('System Admin', 'admin@nexuserp.com', '$2b$10$h0y/7F5hT30LdlyGj9D.3O6p4N3p5M7q8r9s0t1u2v3w4x5y6z7a8', 'ADMIN'),
('Sarah Sales', 'sales@nexuserp.com', '$2b$10$h0y/7F5hT30LdlyGj9D.3O6p4N3p5M7q8r9s0t1u2v3w4x5y6z7a8', 'SALES'),
('Wally Warehouse', 'warehouse@nexuserp.com', '$2b$10$h0y/7F5hT30LdlyGj9D.3O6p4N3p5M7q8r9s0t1u2v3w4x5y6z7a8', 'WAREHOUSE'),
('Alice Accounts', 'accounts@nexuserp.com', '$2b$10$h0y/7F5hT30LdlyGj9D.3O6p4N3p5M7q8r9s0t1u2v3w4x5y6z7a8', 'ACCOUNTS')
ON CONFLICT (email) DO NOTHING;

-- Insert Seed Customers
INSERT INTO customers (name, mobile, email, business_name, gst_number, type, address, status, follow_up_date, notes) VALUES
('John Doe', '+19876543210', 'john@acmedistributors.com', 'Acme Wholesale Corp', '27AAACA12341Z5', 'WHOLESALE', '123 Logistics Blvd, Suite 400, Chicago, IL', 'ACTIVE', '2026-08-05', 'Key wholesale account, prefers bulk monthly shipments.'),
('Jane Smith', '+19876543211', 'jane@apexretail.com', 'Apex Superstores', '27BBACB56782Z6', 'DISTRIBUTOR', '456 Commercial Way, New York, NY', 'LEAD', '2026-08-01', 'Inquired about product pricing for regional stores.'),
('Robert Brown', '+19876543212', 'robert@metrostore.com', 'Metro Retail Outlet', '27CCACC90123Z7', 'RETAIL', '789 Market Street, San Francisco, CA', 'ACTIVE', '2026-08-10', 'Weekly restocking buyer.');

-- Insert Seed Products
INSERT INTO products (name, sku, category, unit_price, current_stock, min_stock_alert, location, image_url) VALUES
('Industrial Hydraulic Valve 50mm', 'IND-VAL-001', 'Industrial Hardware', 149.99, 120, 15, 'Aisle 4, Shelf B', 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=500'),
('Heavy-Duty Steel Bearing Pack', 'IND-BRG-002', 'Bearings & Motors', 89.50, 8, 10, 'Aisle 2, Shelf D', 'https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=500'),
('Digital Pressure Sensor Switch', 'ELE-SNR-003', 'Sensors & Controls', 210.00, 45, 5, 'Aisle 1, Shelf A', 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=500'),
('High-Torque Electric Motor 5HP', 'MTR-5HP-004', 'Bearings & Motors', 520.00, 3, 5, 'Aisle 5, Heavy Storage', 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=500');
